[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2.0", features = ["postgres", "uuid"] }
dotenvy = "0.15"
uuid = { version = "1.7.0", features = ["v4"] }